### ISSUE TITLE
Add support for parsing values

### ISSUE THREAD

**Issue by dominicbarnes** [freeformsystems/cli-argparse#11]
It would be great if values could be run through parse functions, such as coercing strings into numbers. Currently, I need to parse these values afterwards, which is a little clumsy.

One idea:

```js
parse([ '--size', '4' ], {
  parsers: {
    size: function (value) {
      return parseInt(value, 10);
    }
  }
});
```

Maybe some really basic helpers could be added to this lib. (the one above is very common afaik)

```js
parse([' --size', '4' ], {
  parsers: {
    size: parse.number // assumes radix=10
  }
});
```

**Comment by freeformsystems** [comment]
This is easily handled with some post-processing, which is what I do, this library is intentionally meant to be light, you can check out:

https://github.com/freeformsystems/cli-command

For much more comprehensive parsing support via middleware, unfortunately the docs there are very out of date, but there are lots of examples:

https://github.com/freeformsystems/cli-command/tree/master/ebin

Related:

https://github.com/freeformsystems/cli-types
https://github.com/freeformsystems/cli-native

Closing as won't implement.
